spring:
  application:
    name: Online Exam System

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: true

  web:
    resources:
      add-mappings: false
